use_frameworks!

platform :ios, '9.0'

target 'LCCProtocolFinder_Example' do
  pod 'LCCProtocolFinder', :path => '../'

  target 'LCCProtocolFinder_Tests' do
    inherit! :search_paths

    
  end
end
